### ISSUE TITLE
can't compile with libplist 1.11

### ISSUE THREAD

**Issue by winst0nsmith** [libimobiledevice/usbmuxd#21]
i can't compile from source on debian testing. installed sid versions of all dependencies using apt. i'm showing libusbmuxd 1.0.9 and libplist 1.11. i did git clone on the repo to download usbmuxd source, autogen, then at make i get the following error: 

<code>usbmuxd-conf.o: In function `internal_get_value':
/opt/usbmuxd/src/conf.c:289: undefined reference to`plist_read_from_filename'</code>

any hints? been hanging out in irc trying to get help but no luck.i need the newest usbmuxd to run libimobiledevice 1.1.6. only usbmuxd 1.0.8 is available in the debian repos.

thanks in advance
