### ISSUE TITLE
unable to compile with libplist-1.11

### ISSUE THREAD

**Issue by blshkv** [libimobiledevice/usbmuxd#11]
I'm trying to compile the latest HEAD version with ./configure --without-preflight (due to issue #10)
The compilation fails with the following error:

```
libtool: link: x86_64-pc-linux-gnu-gcc -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -I../src -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -march=core2 -mtune=generic -O2 -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o usbmuxd usbmuxd-client.o usbmuxd-device.o usbmuxd-preflight.o usbmuxd-log.o usbmuxd-usb-linux.o usbmuxd-utils.o usbmuxd-conf.o usbmuxd-main.o  -lplist -lusb-1.0 -lpthread
usbmuxd-conf.o: In function `internal_get_value':
/var/tmp/portage/app-pda/usbmuxd-1.0.8_p20140325/work/src/conf.c:289: undefined reference to `plist_read_from_filename'
usbmuxd-conf.o: In function `internal_set_value':
/var/tmp/portage/app-pda/usbmuxd-1.0.8_p20140325/work/src/conf.c:234: undefined reference to `plist_read_from_filename'
collect2: error: ld returned 1 exit status
make[2]: *** [usbmuxd] Error 1
```
