### PR TITLE
build: check if clock_gettime() requires -lrt on old GNU systems

### LINKED ISSUE #98: Does not compile with Ubuntu 12.04
I realize that Ubuntu 12.04 is ancient at this point; but I may have a friend of friend using this ;-P In any case...

When compiling I get:

```
make[2]: Entering directory `/root/chef/usbmuxd/b564c15818a90e31e356756b2a25beb1/src'
  CC     usbmuxd-client.o
  CC     usbmuxd-device.o
  CC     usbmuxd-preflight.o
  CC     usbmuxd-log.o
  CC     usbmuxd-usb.o
  CC     usbmuxd-utils.o
utils.c:331:12: error: static declaration of ‘clock_gettime’ follows non-static declaration
/usr/include/time.h:336:12: note: previous declaration of ‘clock_gettime’ was here
utils.c: In function ‘clock_gettime’:
utils.c:337:2: error: unknown type name ‘mach_timebase_info_data_t’
utils.c:339:2: warning: implicit declaration of function ‘mach_absolute_time’ [-Wimplicit-function-declaration]
utils.c:341:15: error: request for member ‘denom’ in something not a structure or union
utils.c:342:3: warning: implicit declaration of function ‘mach_timebase_info’ [-Wimplicit-function-declaration]
utils.c:345:15: error: request for member ‘numer’ in something not a structure or union
utils.c:345:39: error: request for member ‘denom’ in something not a structure or union
utils.c:348:35: error: request for member ‘numer’ in something not a structure or union
utils.c:348:53: error: request for member ‘denom’ in something not a structure or union
make[2]: *** [usbmuxd-utils.o] Error 1
make[2]: Leaving directory `/root/chef/usbmuxd/b564c15818a90e31e356756b2a25beb1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/chef/usbmuxd/b564c15818a90e31e356756b2a25beb1'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by kamstrup**
Ensures HAVE_CLOCK_GETTIME is set on systems with glibc < 2.17 (Ubuntu 12.04 uses 2.15).

Fixes #98

### CODE REVIEW

**Comment by nikias** [comment]
Merged after rebase. Thanks!
